// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System;
using System.Text;
using System.Diagnostics;
using Microsoft.CodeAnalysis.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using System.Collections.Generic;

namespace RFBCodeWorks.Mvvm.SourceGenerators
{
    internal sealed class SourceWriter
    {
        public const string EditorBrowsableNever = "[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]";
        public const string ExcludeFromCodeCoverage = "[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]";
        private const string _generatedCodeAttributeFormat = "[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"{0}\", \"{1}\")]";
        public static readonly string GeneratedCodeAttribute;
        public static readonly string AutoGeneratedFileHeader;
        private static readonly string _assemblyName;
        private static readonly string _assemblyVersion;

        private const string _fileClosingPragmas = "#pragma warning restore CS0612, CS0618 // restore [Obsolete] warnings";

        static SourceWriter()
        {
            var assy = System.Reflection.Assembly.GetAssembly(typeof(SourceWriter)).GetName();
            _assemblyName = assy.Name;
            _assemblyVersion = assy.Version.ToString();
            GeneratedCodeAttribute = string.Format(_generatedCodeAttributeFormat, assy.Name, assy.Version);
            AutoGeneratedFileHeader = $@"// <auto-generated/>
// Do not edit this file! File generated by: {_assemblyName} v{_assemblyVersion}
//

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618";
        }

        private const char IndentationChar = ' ';
        private const int CharsPerIndentation = 4;

        private readonly StringBuilder _sb = new();
        private readonly Stack<char> _blocks = new();
        private readonly CancellationToken _token;
        private int _indentation;
        private bool _isOnNewLine;
        private bool _fileHeaderWritten;
        
        
        public SourceWriter(CancellationToken token)
        {
            _token = token;
        }

        public string SuggestedFileName { get; private set; }

        public int Indentation
        {
            get => _indentation;
            set
            {
                if (value < 0)
                {
                    Throw();
                    static void Throw() => throw new ArgumentOutOfRangeException(nameof(value));
                }

                _indentation = value;
            }
        }

        /// <summary>
        /// Generates a filename and sets the 'SuggestedFileName' property
        /// </summary>
        /// <param name="symbol"></param>
        public void SetFileName(ISymbol symbol) => SuggestedFileName = SymbolFormats.GetFileName(symbol, includeFileExtension: true);

        /// <summary>
        /// Sets the 'SuggestedFileName' property
        /// </summary>
        /// <param name="symbol"></param>
        public void SetFileName(string fileName) => SuggestedFileName = fileName ?? string.Empty;

        /// <summary>
        /// Close the file (adding '}' per indentation level) then return the source text
        /// </summary>
        public SourceText ToSourceText()
        {
            while (_blocks.Count > 0)
            {
                _token.ThrowIfCancellationRequested();
                EndBlock();
            }
            while (Indentation > 0)
            {
                _token.ThrowIfCancellationRequested();
                Indentation--;
                WriteLine('}');
            }
            if (_fileHeaderWritten)
            {
                WriteLine();
                WriteLine(_fileClosingPragmas);
            }
            Debug.Assert(_indentation == 0 && _sb.Length > 0);
            return SourceText.From(_sb.ToString(), Encoding.UTF8);
        }

        public void Reset()
        {
            _sb.Clear();
            _indentation = 0;
        }

        /// <summary>
        /// Writes the standard file header (no class entry)
        /// </summary>
        public SourceWriter WriteFileHeader()
        {
            WriteLine(AutoGeneratedFileHeader);
            WriteLine();
            _fileHeaderWritten = true;
            return this;
        }

        /// <inheritdoc cref="WriteFileHeader(INamedTypeSymbol, bool, string[])"/>
        public SourceWriter WriteFileHeader(ISymbol symbol) => WriteFileHeader(symbol, Array.Empty<string>());
        
        /// <inheritdoc cref="WriteFileHeader(INamedTypeSymbol, bool, string[])"/>
        public SourceWriter WriteFileHeader(INamedTypeSymbol symbol) => WriteFileHeader(symbol, Array.Empty<string>());

        /// <inheritdoc cref="WriteFileHeader(INamedTypeSymbol, bool, string[])"/>
        public SourceWriter WriteFileHeader(ISymbol symbol, params string[] usings)
        {
            if (symbol is INamedTypeSymbol nt)
            { WriteFileHeader(nt, false, usings); }
            else if (symbol.ContainingType is INamedTypeSymbol ct)
            { WriteFileHeader(ct, false, usings); }
            else Throw();
            SetFileName(symbol);
            return this;
            static void Throw() => throw new ArgumentException("symbol is not contained within a type");
        }

        /// <inheritdoc cref="WriteFileHeader(INamedTypeSymbol, bool, string[])"/>
        public SourceWriter WriteFileHeader(INamedTypeSymbol namedType, params string[] usings) => WriteFileHeader(namedType, true, usings);

        /// <summary>
        /// Writes the file header, including the namespace and partial class entry (with opening braces)
        /// </summary>
        /// <remarks>calls <see cref="SetFileName(ISymbol)"/></remarks>
        /// <param name="symbol"></param>
        /// <param name="usings">
        /// Fully written 'usings' statement. EX : 
        /// <br/> "using System.Text;"
        /// </param>
        /// <param name="setFileName"></param>
        private SourceWriter WriteFileHeader(INamedTypeSymbol symbol, bool setFileName, string[] usings)
        {
            if (symbol is null) throw new ArgumentNullException(nameof(symbol));
            if (symbol.IsNamespace) throw new ArgumentException("expected a type and not a namespace");
            WriteFileHeader();

            if (usings.Length > 0)
            {
                foreach (var line in usings)
                {
                    _sb.AppendLine(line);
                }
                _sb.AppendLine();
                _isOnNewLine = true;
            }

            if (symbol.ContainingNamespace is INamespaceSymbol ns)
            {
                BeginBlock(ns.ToDisplayString(SymbolFormats.NamespaceFormat));
            }

            Stack<INamedTypeSymbol> tree = new();
            var containingType = symbol;
            while (containingType != null)
            {
                _token.ThrowIfCancellationRequested();
                tree.Push(containingType);
                containingType = containingType.ContainingType;
            }
            while (tree.Count > 0)
            {
                _token.ThrowIfCancellationRequested();
                containingType = tree.Pop();
                AddIndentation();
                switch(containingType.DeclaredAccessibility)
                {
                    case Accessibility.NotApplicable: break;
                    case Accessibility.ProtectedOrInternal: _sb.Append("protected internal "); break;
                    case Accessibility.ProtectedAndInternal: _sb.Append("private protected "); break;
                    case Accessibility.Protected: _sb.Append("protected "); break;
                    case Accessibility.Internal: _sb.Append("internal "); break;
                    case Accessibility.Private: _sb.Append("private "); break;
                    case Accessibility.Public: _sb.Append("public "); break;
                }
                if (containingType.IsStatic) _sb.Append("static ");
                if (containingType.IsAbstract) _sb.Append("abstract ");
                if (containingType.IsSealed) _sb.Append("sealed ");
                _sb.Append("partial ");
                _isOnNewLine = false;
                BeginBlock(containingType.ToDisplayString(SymbolFormats.PartialClassEntry));
            }

            if (setFileName) SetFileName(symbol);
            return this;
        }

        public SourceWriter AddObsoleteAttribute(string reason, bool asError = false) => WriteLine("[global::System.Obsolete(\"{0}\", {1})]", reason, asError ? "true" : "false");

        /// <summary>
        /// Creates a new block for a namespace, class declaration, or method/property body.
        /// </summary>
        /// <param name="declaration"></param>
        /// <returns></returns>
        public SourceWriter BeginBlock(string declaration)
        {
            WriteLine(declaration).WriteLine('{').Indentation++;
            _blocks.Push('}');
            return this;
        }
        /// <summary>
        /// Creates a new block using the specified <paramref name="blockStart"/> character.
        /// <br/>Close this block using <see cref="EndBlock"/>
        /// </summary>
        public SourceWriter BeginBlock(string declaration, char blockStart = '{', bool moveToNewLine = true)
        {
            if (moveToNewLine)
            {
                WriteLine(declaration);
                WriteLine(blockStart);
            }
            else
            {
                AddIndentation();
                _sb.Append(declaration.TrimEnd()).Append(' ').Append(blockStart);
                _isOnNewLine = false;
            }
            Indentation++;
            _blocks.Push(blockStart switch
            {
                '(' => ')',
                _ => '}'
            });
            return this;
        }

        /// <summary>Ends the current block</summary>
        public SourceWriter EndBlock()
        {
            if (_blocks.Count == 0) throw new InvalidOperationException("No more blocks to end");
            Indentation--;
            return WriteLine(_blocks.Pop());
        }
        /// <summary>Ends the current block. Conditionally moves to a new line after the block character is written</summary>
        public SourceWriter EndBlock(bool moveToNewLine, bool addSemiColon = false)
        {
            if (_blocks.Count == 0) throw new InvalidOperationException("No more blocks to end");
            if (moveToNewLine && !_isOnNewLine)
            {
                _sb.AppendLine();
                _isOnNewLine=true;
            }
            if (_isOnNewLine)
            {
                Indentation--;
                AddIndentation();
            }
            char c = _blocks.Pop();
            _sb.Append(c);
            if (c == ')' && addSemiColon) _sb.Append(';');
            if (moveToNewLine)
            {
                _sb.AppendLine();
                _isOnNewLine = true;
            }
            return this;
        }

        public SourceWriter Write(char value) { _sb.Append(value); _isOnNewLine = false; return this; }
        public SourceWriter Write(string value) { _sb.Append(value); _isOnNewLine = false; return this; }
        public SourceWriter Write(string format, string arg1) { _sb.AppendFormat(format, arg1); _isOnNewLine = false; return this; }
        public SourceWriter Write(string format, string arg1, string arg2) { _sb.AppendFormat(format, arg1, arg2); _isOnNewLine = false; return this; }
        public SourceWriter Write(string format, params string[] args) { _sb.AppendFormat(format, args); _isOnNewLine = false; return this; }

        public SourceWriter WriteLine(char value)
        {
            AddIndentation();
            _sb.Append(value);
            _sb.AppendLine();
            _isOnNewLine = true;
            return this;
        }
        
        public SourceWriter WriteLine(string text)
        {
            if (_indentation == 0)
            {
                _sb.AppendLine(text);
                _isOnNewLine = true;
                return this;
            }

            bool isFinalLine;
            ReadOnlySpan<char> remainingText = text.AsSpan();
            do
            {
                _token.ThrowIfCancellationRequested();
                ReadOnlySpan<char> nextLine = GetNextLine(ref remainingText, out isFinalLine);

                AddIndentation();
                AppendSpan(_sb, nextLine);
                _sb.AppendLine();
                _isOnNewLine = true;
            }
            while (!isFinalLine);
            return this;
        }

        /// <inheritdoc cref="WriteLine(string, string[])"/>
        public SourceWriter WriteLine(string format, string arg1)
        {
            if (_indentation > 0) AddIndentation();
            _sb.AppendFormat(format, arg1);
            _sb.AppendLine();
            _isOnNewLine = true;
            return this;
        }

        /// <inheritdoc cref="WriteLine(string, string[])"/>
        public SourceWriter WriteLine(string format, string arg1, string arg2)
        {
            if (_indentation > 0) AddIndentation();
            _sb.AppendFormat(format, arg1, arg2);
            _sb.AppendLine();
            _isOnNewLine = true;
            return this;
        }

        /// <summary>
        /// Write a formatted expression to the file.
        /// </summary>
        /// <remarks>The formatted expression should be on a single line.</remarks>
        /// <param name="format">A formatted expression that represents 1 line.</param>
        /// <param name="args"></param>
        /// <returns>The <see cref="SourceWriter"/></returns>
        public SourceWriter WriteLine(string format, params string[] args)
        {
            if (_indentation > 0) AddIndentation();
            _sb.AppendFormat(format, args);
            _sb.AppendLine();
            _isOnNewLine = true;
            return this;
        }

        public SourceWriter WriteLine()
        {
            _sb.AppendLine();
            _isOnNewLine = true;
            return this;
        }

        /// <summary>
        /// Write a parameter using the specified <paramref name="format"/>
        /// </summary>
        /// <param name="parameterSymbol"></param>
        /// <param name="format"></param>
        /// <param name="includeSeparator">set true to append ", " after the parameter</param>
        /// <param name="asNewLine">
        /// <see langword="true"/> : {indent} {parameter} {newline}
        /// <br/> <see langword="false"/> : {parameter}
        /// </param>
        /// <param name="defaultValue">default value string " = value" to append if the parameter does not have an <see cref="IParameterSymbol.HasExplicitDefaultValue"/></param>
        /// <returns></returns>
        public SourceWriter WriteSymbol(IParameterSymbol parameterSymbol, SymbolDisplayFormat format, bool includeSeparator, bool asNewLine, string defaultValue = "")
        {
            if (asNewLine && _indentation > 0) AddIndentation();
            _isOnNewLine = false;
            _sb.Append(parameterSymbol.ToDisplayString(format));
            if (string.IsNullOrWhiteSpace(defaultValue) == false && (!parameterSymbol.HasExplicitDefaultValue | !format.ParameterOptions.HasFlag(SymbolDisplayParameterOptions.IncludeDefaultValue)))
            {
                _sb.Append(defaultValue);
            }
            if (includeSeparator) _sb.Append(", ");
            if (asNewLine)
            {
                _sb.AppendLine();
                _isOnNewLine = true;
            }
            return this;
        }

        /// <summary>
        /// Write a method invoker
        /// </summary>
        /// <param name="methodSymbol">the method to write</param>
        /// <param name="prefix">A prefix to write before writing the method display string.</param>
        /// <param name="format">
        /// The format to write the method with.
        /// <br/> - <see cref="SymbolFormats.MethodInvokeFullyQualified"/>
        /// <br/> - <see cref="SymbolFormats.MethodInvokePrivate"/>
        /// </param>
        /// <param name="isStartOfLine">if true indents the line.</param>
        /// <param name="isEndOfLine">if true : ends the line with ";"</param>
        /// <returns></returns>
        public SourceWriter WriteSymbol(IMethodSymbol methodSymbol, SymbolDisplayFormat format, bool isStartOfLine, bool isEndOfLine, string prefix = "")
        {
            if (isStartOfLine && _indentation > 0) AddIndentation();
            _isOnNewLine = false;
            if (!string.IsNullOrWhiteSpace(prefix)) _sb.Append(prefix);
            _sb.Append(methodSymbol.ToDisplayString(format));
            if (isEndOfLine)
            {
                _sb.Append(';').AppendLine();
                _isOnNewLine = true;
            }
            return this;
        }

        /// <summary>
        /// Writes the method signature based on the provided formats
        /// </summary>
        /// <param name="methodSymbol"></param>
        /// <param name="methodFormat">the method format to apply</param>
        /// <param name="returnTypeFormat">optional return type format. use null if not specified.</param>
        /// <param name="parameterFormat">optional parameter format to apply to each parameter. If not null, also adds the () to the writer.</param>
        /// <param name="isPartialMethod">if true, indents the line and adds 'partial' before the return type.</param>
        /// <remarks>Does NOT move to the next line.</remarks>
        public SourceWriter WriteSymbol(IMethodSymbol methodSymbol, SymbolDisplayFormat methodFormat, SymbolDisplayFormat? returnTypeFormat = null, SymbolDisplayFormat? parameterFormat = null, bool isPartialMethod = false)
        {
            var membersToExclude = parameterFormat is null ? SymbolDisplayMemberOptions.None : SymbolDisplayMemberOptions.IncludeParameters;

            // write the method signature
            if (isPartialMethod || methodSymbol.IsPartialDefinition)
            {
                if (_indentation > 0) AddIndentation();
                if (methodFormat.MemberOptions.HasFlag(SymbolDisplayMemberOptions.IncludeModifiers))
                {
                    WriteSymbolModifiers(methodSymbol, isPartialMethod);
                    membersToExclude |= SymbolDisplayMemberOptions.IncludeModifiers;
                }
                else
                {
                    _sb.Append("partial ");
                }
            }
            _isOnNewLine = false;

            if (returnTypeFormat is not null)
            {
                _sb.Append(methodSymbol.ReturnType.ToDisplayString(returnTypeFormat)).Append(' ');
                membersToExclude |= SymbolDisplayMemberOptions.IncludeType;
            }

            if (membersToExclude != SymbolDisplayMemberOptions.None)
            {
                methodFormat = methodFormat.WithMemberOptions(methodFormat.MemberOptions & ~membersToExclude);
            }
            _sb.Append(methodSymbol.ToDisplayString(methodFormat));
            if (parameterFormat is not null)
            {
                _sb.Append('(');
                int lastParam = methodSymbol.Parameters.Length - 1;
                for (int i = 0; i < methodSymbol.Parameters.Length; i++)
                {
                    WriteSymbol(methodSymbol.Parameters[i], parameterFormat, i < lastParam, false);
                }
                _sb.Append(')');
            }
            return this;
        }

        /// <summary>
        /// Writes the <see cref="ISymbol"/> modifiers
        /// </summary>
        /// <param name="isPartial">include the 'partial' keyword or not</param>
        /// <returns></returns>
        public SourceWriter WriteSymbolModifiers(ISymbol symbol, bool isPartial = false)
        {
            switch (symbol.DeclaredAccessibility)
            {
                case Accessibility.NotApplicable: break;
                case Accessibility.ProtectedOrInternal: _sb.Append("protected internal "); break;
                case Accessibility.ProtectedAndInternal: _sb.Append("private protected "); break;
                case Accessibility.Protected: _sb.Append("protected "); break;
                case Accessibility.Internal: _sb.Append("internal "); break;
                case Accessibility.Private: _sb.Append("private "); break;
                case Accessibility.Public: _sb.Append("public "); break;
            }
            if (symbol.IsStatic) _sb.Append("static ");
            if (symbol.IsAbstract || symbol.IsVirtual || symbol.IsOverride) _sb.Append("override ");
            if (symbol.IsSealed) _sb.Append("sealed ");
            if (symbol.IsExtern) _sb.Append("extern ");
            if (symbol is IMethodSymbol ms)
            {
                if (ms.IsAsync) _sb.Append("async ");
                if (ms.IsPartialDefinition || isPartial) _sb.Append("partial ");
            }
            else if (isPartial)
            {
                _sb.Append("partial ");
            }
            _isOnNewLine = false;
            return this;
        }

        public SourceWriter WriteIndent()
        {
            if (_isOnNewLine && _indentation > 0) AddIndentation();
            return this;
        }

        private void AddIndentation()
        {
            if (_isOnNewLine) _sb.Append(IndentationChar, CharsPerIndentation * _indentation);
            _isOnNewLine = false;
        }

        private static ReadOnlySpan<char> GetNextLine(ref ReadOnlySpan<char> remainingText, out bool isFinalLine)
        {
            if (remainingText.IsEmpty)
            {
                isFinalLine = true;
                return default;
            }

            ReadOnlySpan<char> next;
            ReadOnlySpan<char> rest;

            int lineLength = remainingText.IndexOf('\n');
            if (lineLength == -1)
            {
                lineLength = remainingText.Length;
                isFinalLine = true;
                rest = default;
            }
            else
            {
                rest = remainingText.Slice(lineLength + 1);
                isFinalLine = false;
            }

            if ((uint)lineLength > 0 && remainingText[lineLength - 1] == '\r')
            {
                lineLength--;
            }

            next = remainingText.Slice(0, lineLength);
            remainingText = rest;
            return next;
        }

        private static unsafe void AppendSpan(StringBuilder builder, ReadOnlySpan<char> span)
        {
            // There is no StringBuilder.Append(ReadOnlySpan<char>) overload in the NS2.0
            fixed (char* ptr = span)
            {
                builder.Append(ptr, span.Length);
            }
        }
    }
}