using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using RFBCodeWorks.Mvvm.SourceGenerators.Refreshable;
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading;

namespace RFBCodeWorks.Mvvm.SourceGenerators.Refreshable
{
    /// <summary>
    /// Emits On(PropName)Changed(returnType value) methods
    /// </summary>
    internal class TriggerRefreshEmitter
    {
        private readonly CancellationToken _token;

        public SourceWriter Writer { get; private set; }

        public TriggerRefreshEmitter(CancellationToken token)
        {
            _token = token;
        }

        public void Emit(TriggersRefreshData data, Action<Diagnostic> reportDiag)
        {
            if (data.TargetNode is not VariableDeclaratorSyntax variable) return;
            if (data.TargetSymbol is not IFieldSymbol fieldSymbol) return;
            if (data.Any is false) return;

            string returnType = null;
            //foreach (var variable in fieldDeclaration.Declaration.Variables)
            //{
            _token.ThrowIfCancellationRequested();

            //if (data.SemanticModel.GetSymbolInfo(variable, _token).Symbol is not IFieldSymbol fieldSymbol) continue;

            if (Diagnostics.TryGetPropertyName(fieldSymbol, "", out string propName) is Diagnostic d)
            {
                reportDiag(d);
                return;
            }
            returnType ??= fieldSymbol.Type.ToDisplayString(SymbolFormats.FullyQualifiedFormat);

            if (Writer is null)
            {
                Writer = new SourceWriter(_token).WriteFileHeader(fieldSymbol.ContainingType);
            }
            else
            {
                Writer.WriteLine();
            }

            Writer
                .WriteLine("/// <remarks> Generated method that triggers refresh on various RefreshableSelector objects </remarks>")
                .WriteLine("/// Generated by {0}, v{1}", SourceWriter._assemblyName, SourceWriter._assemblyVersion)
                .BeginBlock($"partial void On{propName}Changed({returnType} value)");

            WriteRefreshTriggers(Writer, data, _token);
            Writer.EndBlock();
        }

        /// <summary>
        /// Invokes the RefreshCommand.Execute method on any RefreshableSelectors specified
        /// </summary>
        public static void WriteRefreshTriggers(SourceWriter writer, in TriggersRefreshData data, CancellationToken token)
        {
            if (!data.TargetsToRefresh.IsDefaultOrEmpty)
            {
                foreach (var item in data.TargetsToRefresh)
                {
                    token.ThrowIfCancellationRequested();
                    writer.WriteLine("{0}?.RefreshCommand?.Execute(null);".AsSpan(), item.AsSpan());
                }
            }
        }
    }
}
