using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using WebView = Microsoft.Web.WebView2.Core;

namespace RFBCodeWorks.WPF.WebView2Integration
{
    /// <summary>
    /// Basic handler for navigation events generated by WebView2
    /// </summary>
    /// <remarks>
    /// <seealso href="https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/navigation-events"/>
    /// </remarks>
    public interface IWebView2NavigationHandler
    {
        /// <summary>
        /// Handle <see cref="WebView.CoreWebView2.NavigationStarting"/>
        /// </summary>
        /// <remarks>
        /// <inheritdoc cref="WebView.CoreWebView2.NavigationStarting" path="/summary"/>
        /// </remarks>
        void OnNavigationStarting(object sender, WebView.CoreWebView2NavigationStartingEventArgs e);

        /// <summary>
        /// Handle <see cref="WebView.CoreWebView2.NavigationCompleted"/>
        /// </summary>
        /// <remarks>
        /// <inheritdoc cref="WebView.CoreWebView2.NavigationCompleted" path="/summary"/>
        /// </remarks>
        void OnNavigationCompleted(object sender, WebView.CoreWebView2NavigationCompletedEventArgs e);
    }

    /// <summary>
    /// Basic handler for navigation events generated by WebView2
    /// </summary>
    /// <remarks>
    /// <seealso href="https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/navigation-events"/>
    /// </remarks>
    public interface IWebView2NavigationHandlerExpanded : IWebView2NavigationHandler
    {
        void OnBasicAuthenticationRequested(object sender, Microsoft.Web.WebView2.Core.CoreWebView2BasicAuthenticationRequestedEventArgs e);
        void OnCoreWebView2InitializationCompleted(object sender, Microsoft.Web.WebView2.Core.CoreWebView2InitializationCompletedEventArgs e);
        void OnHistoryChanged(object sender, object e);
        void OnWebMessageReceived(object sender, Microsoft.Web.WebView2.Core.CoreWebView2WebMessageReceivedEventArgs e);
        void OnSourceChanged(object sender, Microsoft.Web.WebView2.Core.CoreWebView2SourceChangedEventArgs e);
        void OnContentLoading(object sender, Microsoft.Web.WebView2.Core.CoreWebView2ContentLoadingEventArgs e);
    }

}