// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System;
using System.Text;
using System.Diagnostics;
using Microsoft.CodeAnalysis.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.CompilerServices;

#nullable enable
#nullable disable warnings
namespace RFBCodeWorks.Mvvm.SourceGenerators
{
    [DefaultValue(1)]
    [Flags]
    public enum Attributes
    {
        /// <inheritdoc cref="SourceWriter.GeneratedCodeAttribute"/>
        GeneratedCodeAttribute = 1,

        /// <inheritdoc cref="SourceWriter.EditorBrowsableNever"/>
        EditorBrowsableNever = 2,
        
        /// <inheritdoc cref="SourceWriter.ExcludeFromCodeCoverage"/>
        ExcludeFromCodeCoverage = 4,
        
        /// <inheritdoc cref="SourceWriter.DebuggerHidden"/>
        DebuggerHidden = 8,
        
        /// <inheritdoc cref="SourceWriter.DebuggerStepThrough"/>
        DebuggerStepThroughAttribute = 16,
    }

    /// <summary>
    /// A Source Writer to generate source code files
    /// </summary>
    /// <remarks>
    /// Best Practices (based on benchmarks):
    /// <br/> - Avoid String.Format().
    /// <br/> - Avoid interpolated strings with more than 3 arguments unless using WriteFormattable().
    /// <br/> - Prefer to use overloads that accept a 'format' with args.
    /// </remarks>
    public sealed class SourceWriter
    {
        /// <summary> Prevent the user from viewing the mebmber within the editor </summary>
        public const string EditorBrowsableNever = "[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]";

        /// <summary> Exclude the code from analyzer coverage </summary>
        /// <remarks> Can not apply to fields. </remarks>
        public const string ExcludeFromCodeCoverage = "[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]";

        /// <summary> Attribute to prevent the debugger from hitting any breakpoints within the property or method </summary>
        public const string DebuggerHidden = "[global::System.Diagnostics.DebuggerHidden]";
        
        /// <summary> Attribute to prevent the debugger from hitting any breakpoints a specified method - should only be applied to method declarations</summary>
        public const string DebuggerStepThrough = "[global::System.Diagnostics.DebuggerStepThrough]";

        private const string _generatedCodeAttributeFormat = "[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"{0}\", \"{1}\")]";
        public static readonly string GeneratedCodeAttribute;
        public static readonly string AutoGeneratedFileHeader;
        public static readonly string _assemblyName;
        public static readonly string _assemblyVersion;

        private const string _fileClosingPragmas = "#pragma warning restore CS0612, CS0618 // restore [Obsolete] warnings";

        static SourceWriter()
        {
            var assy = System.Reflection.Assembly.GetAssembly(typeof(SourceWriter)).GetName();
            _assemblyName = assy.Name;
            _assemblyVersion = assy.Version.ToString();
            GeneratedCodeAttribute = string.Format(_generatedCodeAttributeFormat, assy.Name, assy.Version);
            AutoGeneratedFileHeader = $@"// <auto-generated/>
// Do not edit this file! File generated by: {_assemblyName} v{_assemblyVersion}
//

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618";
        }

        private const char IndentationChar = ' ';
        private const int CharsPerIndentation = 4;

        private readonly StringBuilder _sb = new();
        private readonly Stack<char> _blocks = new();
        private readonly CancellationToken _token;
        private int _indentation;
        private bool _isOnNewLine;
        private bool _fileHeaderWritten;
        
        
        public SourceWriter(CancellationToken token)
        {
            _token = token;
        }

        public string SuggestedFileName { get; private set; }

        public int Indentation
        {
            get => _indentation;
            set
            {
                if (value < 0)
                {
                    Throw();
                    static void Throw() => throw new ArgumentOutOfRangeException(nameof(value));
                }

                _indentation = value;
            }
        }

        public SourceWriter AddObsoleteAttribute(string reason, bool asError = false) => WriteLine("[global::System.Obsolete(\"{0}\", {1})]", reason, asError ? "true" : "false");

        /// <summary>
        /// Writes the <paramref name="declaration"/> to the current line, then writes '{' to the next line.
        /// </summary>
        /// <param name="declaration">The text to write onto the current line prior to the open brace.</param>
        /// <returns>
        /// <br/><paramref name="declaration"/>
        /// <br/>{
        /// </returns>
        /// <remarks>
        /// Example: declaration = "var x = new y()"
        /// <br/> var x = new y()
        /// <br/> {
        /// </remarks>
        public SourceWriter BeginBlock(string declaration)
        {
            WriteLine(declaration.TrimEnd()).WriteLine('{').Indentation++;
            _blocks.Push('}');
            return this;
        }

        public SourceWriter BeginBlock(INamespaceSymbol namespaceSymbol) => BeginBlock(namespaceSymbol.ToDisplayString(SymbolFormats.NamespaceFormat));

        private static char ThrowInvalidBlockChar(char arg) => throw new ArgumentException($"Invalid block start character: {arg}. Only '{{' or '(' are supported.", "blockStart");
        private static void ThrowBlockException() => throw new InvalidOperationException("No more blocks to end");

        /// <summary>
        /// Writes a the text to the writer, then opens the block
        /// </summary>
        /// <param name="declaration">
        /// this text is always written to the current line.
        /// <br/> - If <paramref name="moveToNewLine"/> is specified, the cursor moves to the next line prior to beginning the block.
        /// </param>
        /// <param name="blockStart">
        /// The character to use when opening the block. '{' or '('
        /// <br/> - If <paramref name="moveToNewLine"/> is specified, this brace will be on its own line, otherwise it will occur after the <paramref name="declaration"/>.
        /// </param>
        /// <param name="moveToNewLine"/>
        /// <returns>
        /// <paramref name="moveToNewLine"/> = <see langword="true"/> (default) :
        /// <br/><paramref name="declaration"/>
        /// <br/>{
        /// <para/>
        /// <paramref name="moveToNewLine"/> = <see langword="false"/> : 
        /// <br/><paramref name="declaration"/> {
        /// </returns>
        public SourceWriter BeginBlock(string declaration = "", char blockStart = '{', bool moveToNewLine = true)
        {
            char endChar = blockStart switch
            {
                '{' => '}',
                '(' => ')',
                _ => ThrowInvalidBlockChar(blockStart),
            };

            if (moveToNewLine)
            {
                // logic prevents writing an empty line 
                if (declaration.IsNotEmptyOrWhiteSpace())
                {
                    IndentIfOnNewLine();
                    _sb.AppendLine(declaration.TrimEnd());
                }
                else if (!_isOnNewLine)
                {
                    _sb.AppendLine();
                }
                _isOnNewLine = true;
                WriteLine(blockStart);
            }
            else
            {
                IndentIfOnNewLine();
                if (declaration.IsNotEmptyOrWhiteSpace())
                {
                    _sb.Append(declaration.TrimEnd());
                    if (blockStart == '{') _sb.Append(' ');
                }
                _sb.Append(blockStart);
                _isOnNewLine = false;
            }

            Indentation++;
            _blocks.Push(endChar);  // Simplified and more explicit
            return this;
        }

        /// <summary>Writes the character to end the current block, then moves to the next line.</summary>
        public SourceWriter EndBlock()
        {
            if (_blocks.Count == 0) ThrowBlockException();
            Indentation--;
            return WriteLine(_blocks.Pop());
        }

        /// <summary>
        /// Ends the current block.
        /// <br/> Conditionally moves to a new line after the block character is written.
        /// <br/> Allows for writing a semicolon to the end of the block.
        /// </summary>
        /// <param name="moveToNewLine">
        /// Note : this should be true for most cases.
        /// When <see langword="true"/>, move to a new line prior to writing the end of the block.
        /// <br/>When <see langword="false"/>, the end of the block will be on the current line.
        /// <para/>Also controls moving to a new line after this block has been completed. 
        /// <br/>When <see langword="false"/>, you must move to the next manually via <see cref="WriteLine()"/>
        /// </param>
        /// <param name="addSemiColon">Add a semicolon after then end of the block (method calls or constructors w/ properties)</param>
        /// <returns>
        /// <paramref name="moveToNewLine"/> = <see langword="true"/>:
        /// <br/>/*starting line*/
        /// <br/>}
        /// <br/>/*cursor*/
        /// <para/>
        /// <paramref name="moveToNewLine"/> = <see langword="false"/> : 
        /// <br/>/*starting line*/ } /*cursor*/
        /// </returns>
        /// <exception cref="InvalidOperationException"></exception>
        public SourceWriter EndBlock(bool moveToNewLine, bool addSemiColon = false)
        {
            if (_blocks.Count == 0) ThrowBlockException();
            
            char c = _blocks.Pop();
            Indentation--;

            if (_isOnNewLine)
            {
                Indent();
            }
            else if (moveToNewLine)
            {
                _sb.AppendLine();
                Indent();
            }
            else if (c == '}')
            {
                // when appending a single line curly brace, place a space between brace and prior text
                _sb.Append(' ');
            }

            _sb.Append(c);
            if (addSemiColon) _sb.Append(';');

            if (moveToNewLine)
            {
                _sb.AppendLine();
                _isOnNewLine = true;
            }
            return this;
        }

        /// <summary>
        /// Immediately write the indent to the line
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Indent()
        {
            _sb.Append(IndentationChar, CharsPerIndentation * _indentation);
            _isOnNewLine = false;
        }

        /// <summary>
        /// Wraps <see cref="Indent"/> with a logic statement to check for <see cref="_isOnNewLine"/>
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private void IndentIfOnNewLine()
        {
            if (_isOnNewLine && Indentation > 0) Indent();
        }

        public void Reset()
        {
            _sb.Clear();
            _indentation = 0;
        }

        /// <summary>
        /// Generates a filename and sets the 'SuggestedFileName' property
        /// </summary>
        /// <param name="symbol"></param>
        public void SetFileName(ISymbol symbol) => SuggestedFileName = SymbolFormats.GetFileName(symbol, includeFileExtension: true);

        /// <summary>
        /// Sets the 'SuggestedFileName' property
        /// </summary>
        /// <param name="symbol"></param>
        public void SetFileName(string fileName) => SuggestedFileName = fileName ?? string.Empty;

        /// <summary>
        /// Close the file (adding '}' per indentation level) then return the source text
        /// </summary>
        public SourceText ToSourceText()
        {
            while (_blocks.Count > 0)
            {
                _token.ThrowIfCancellationRequested();
                EndBlock();
            }
            while (Indentation > 0)
            {
                _token.ThrowIfCancellationRequested();
                Indentation--;
                WriteLine('}');
            }
            if (_fileHeaderWritten)
            {
                WriteLine();
                WriteLine(_fileClosingPragmas);
            }
            //Debug.Assert(_indentation == 0 && _sb.Length > 0);
            return SourceText.From(_sb.ToString(), Encoding.UTF8);
        }

        /// <summary>
        /// Get the curerent text of the writer
        /// </summary>
        /// <returns>The underlying StringBuilder's current state</returns>
        public override string ToString() => this._sb.ToString();

        /// <summary>
        /// Writes the standard file header (no class entry)
        /// </summary>
        public SourceWriter WriteFileHeader()
        {
            WriteLine(AutoGeneratedFileHeader);
            WriteLine();
            _fileHeaderWritten = true;
            return this;
        }

        /// <inheritdoc cref="WriteFileHeader(INamedTypeSymbol, bool, string[])"/>
        public SourceWriter WriteFileHeader(ISymbol symbol) => WriteFileHeader(symbol, Array.Empty<string>());
        
        /// <inheritdoc cref="WriteFileHeader(INamedTypeSymbol, bool, string[])"/>
        public SourceWriter WriteFileHeader(INamedTypeSymbol symbol) => WriteFileHeader(symbol, Array.Empty<string>());

        /// <inheritdoc cref="WriteFileHeader(INamedTypeSymbol, bool, string[])"/>
        public SourceWriter WriteFileHeader(ISymbol symbol, params string[] usings)
        {
            if (symbol is INamedTypeSymbol nt)
            { WriteFileHeader(nt, false, usings); }
            else if (symbol.ContainingType is INamedTypeSymbol ct)
            { WriteFileHeader(ct, false, usings); }
            else Throw(symbol);

            SetFileName(symbol);
            return this;
            static void Throw(ISymbol symbol) => throw new ArgumentException($"symbol '{symbol.ToDisplayString()}' is not an INamedTypeSymbol or contained within an INamedTypeSymbol");
        }

        /// <inheritdoc cref="WriteFileHeader(INamedTypeSymbol, bool, string[])"/>
        public SourceWriter WriteFileHeader(INamedTypeSymbol namedType, params string[] usings) => WriteFileHeader(namedType, true, usings);

        /// <summary>
        /// Writes the file header, including the namespace and partial class entry (with opening braces)
        /// </summary>
        /// <remarks>calls <see cref="SetFileName(ISymbol)"/></remarks>
        /// <param name="symbol"></param>
        /// <param name="usings">
        /// Fully written 'usings' statement. EX : 
        /// <br/> "using System.Text;"
        /// </param>
        /// <param name="setFileName"></param>
        private SourceWriter WriteFileHeader(INamedTypeSymbol symbol, bool setFileName, string[] usings)
        {
            if (symbol is null) throw new ArgumentNullException(nameof(symbol));
            if (symbol.IsNamespace) throw new ArgumentException("expected a type and not a namespace");
            WriteFileHeader();

            if (usings.Length > 0)
            {
                foreach (var line in usings)
                {
                    _sb.AppendLine(line);
                }
                _sb.AppendLine();
                _isOnNewLine = true;
            }

            WriteClassEntry(symbol, true);
            
            if (setFileName) SetFileName(symbol);
            return this;
        }

        /// <summary>
        /// Writes the Class entry starting at the namespace and continuing until the specified symbol.
        /// </summary>
        /// <param name="symbol"></param>
        /// <param name="beginBlock">
        /// When set true, begins the next block.
        /// <br/> When set false, stays on the same line after writing the entry to the class
        /// </param>
        /// <returns>The same instance</returns>
        public SourceWriter WriteClassEntry(INamedTypeSymbol symbol, bool beginBlock)
        {
            if (symbol.ContainingNamespace is INamespaceSymbol ns)
            {
                BeginBlock(ns.ToDisplayString(SymbolFormats.NamespaceFormat));
            }

            Stack<INamedTypeSymbol> tree = new();
            var containingType = symbol;
            while (containingType != null)
            {
                _token.ThrowIfCancellationRequested();
                tree.Push(containingType);
                containingType = containingType.ContainingType;
            }
            while (tree.Count > 0)
            {
                _token.ThrowIfCancellationRequested();
                containingType = tree.Pop();
                IndentIfOnNewLine();
                switch (containingType.DeclaredAccessibility)
                {
                    case Accessibility.NotApplicable: break;
                    case Accessibility.ProtectedOrInternal: _sb.Append("protected internal "); break;
                    case Accessibility.ProtectedAndInternal: _sb.Append("private protected "); break;
                    case Accessibility.Protected: _sb.Append("protected "); break;
                    case Accessibility.Internal: _sb.Append("internal "); break;
                    case Accessibility.Private: _sb.Append("private "); break;
                    case Accessibility.Public: _sb.Append("public "); break;
                }
                if (containingType.IsStatic) _sb.Append("static ");
                if (containingType.IsAbstract) _sb.Append("abstract ");
                if (containingType.IsSealed) _sb.Append("sealed ");
                _sb.Append("partial ");
                _isOnNewLine = false;

                if (tree.Count > 0 || beginBlock)
                    BeginBlock(containingType.ToDisplayString(SymbolFormats.PartialClassEntry));
                else
                    _sb.Append(containingType.ToDisplayString(SymbolFormats.PartialClassEntry));
            }
            return this;
        }

        public SourceWriter WriteAttributes(Attributes attributes)
        {
            //if (attributes.HasFlag(Attributes.GeneratedCodeAttribute)) // 1
              WriteLine(GeneratedCodeAttribute);// always write this one

            if (attributes.HasFlag(Attributes.EditorBrowsableNever)) // 2
                WriteLine(EditorBrowsableNever);

            if (attributes.HasFlag(Attributes.ExcludeFromCodeCoverage)) // 4
                WriteLine(ExcludeFromCodeCoverage);

            if (attributes.HasFlag(Attributes.DebuggerHidden))  // 8
                WriteLine(DebuggerHidden);

            if (attributes.HasFlag(Attributes.DebuggerStepThroughAttribute)) //16
                WriteLine(DebuggerStepThrough);

            return this;
        }

        /// <summary> Appends the span to the writer </summary>
        public SourceWriter Write(ReadOnlySpan<char> span) { AppendSpan(_sb, span); _isOnNewLine = false; return this; }

        /// <inheritdoc cref="AppendFormat(StringBuilder, ReadOnlySpan{char}, ReadOnlySpan{char}, ReadOnlySpan{char}, ReadOnlySpan{char})"/>
        public SourceWriter Write(ReadOnlySpan<char> format, ReadOnlySpan<char> arg1, ReadOnlySpan<char> arg2 = default, ReadOnlySpan<char> arg3 = default)
        {
            AppendFormat(_sb, format, arg1, arg2, arg3);
            _isOnNewLine = false;
            return this;
        }

        /// <summary> Write a single char </summary>
        public SourceWriter Write(char text) { _sb.Append(text); _isOnNewLine = false; return this; }
        
        /// <summary> Append the text </summary>
        /// <remarks>
        /// If using an interpolated string, prefer other overloads.
        /// </remarks>
        public SourceWriter Write(string text) { _sb.Append(text); _isOnNewLine = false; return this; }

        /// <summary> Append the text via StringBuilder.AppendFormat </summary>
        /// <remarks> This is more efficient that an interpolated string with 1 arg</remarks>
        public SourceWriter Write(string format, string arg1) { _sb.AppendFormat(format, arg1); _isOnNewLine = false; return this; }

        /// <summary> Append the text via StringBuilder.AppendFormat </summary>
        /// <remarks> This is more efficient that an interpolated string with 2 args </remarks>
        public SourceWriter Write(string format, string arg1, string arg2) { _sb.AppendFormat(format, arg1, arg2); _isOnNewLine = false; return this; }

        /// <summary> Append the text via StringBuilder.AppendFormat </summary>
        /// <remarks> 
        /// This is more efficient that an interpolated string with 3 or more args. 
        /// <br/>Use the 'WriteFormattable' method for better readability with 4 or more args.
        /// </remarks>
        public SourceWriter Write(string format, params string[] args) { _sb.AppendFormat(format, args); _isOnNewLine = false; return this; }

        /// <summary>
        /// Write the interpolated string to the builder using AppendFormat
        /// </summary>
        /// <remarks>
        /// This is more efficent than writing an interpolated string with more than 3 arguments, but less efficient than using the <see cref="Write(string, string[])"/> overload.
        /// </remarks>
        public SourceWriter WriteFormattable(FormattableString interpolatedString)
        {
             _sb.AppendFormat(interpolatedString.Format, interpolatedString.GetArguments()); 
            _isOnNewLine = false; 
            return this; 
        }

        /// <summary>
        /// Write the interpolated string to the builder using AppendFormat
        /// </summary>
        /// <remarks>
        /// This is more efficent than writing an interpolated string with more than 3 arguments, but less efficient than using the <see cref="WriteLine(string, string[])"/> overload.
        /// </remarks>
        public SourceWriter WriteFormattableLine(FormattableString interpolatedString)
        {
            if (_isOnNewLine && _indentation > 0) Indent();
            _sb.AppendFormat(interpolatedString.Format, interpolatedString.GetArguments());
            _sb.AppendLine();
            _isOnNewLine = true;
            return this;
        }

        /// <summary> Appends the span to the writer, then moves to the next line. </summary>
        public SourceWriter WriteLine(ReadOnlySpan<char> span)
        {
            if (_isOnNewLine && _indentation > 0) Indent();
            AppendSpan(_sb, span);
            _sb.AppendLine();
            _isOnNewLine = true; 
            return this; 
        }

        /// <inheritdoc cref="AppendFormat(StringBuilder, ReadOnlySpan{char}, ReadOnlySpan{char}, ReadOnlySpan{char}, ReadOnlySpan{char})"/>
        public SourceWriter WriteLine(ReadOnlySpan<char> formatSpan, ReadOnlySpan<char> arg1, ReadOnlySpan<char> arg2 = default, ReadOnlySpan<char> arg3 = default)
        {
            if (_isOnNewLine && _indentation > 0) Indent();
            AppendFormat(_sb, formatSpan, arg1, arg2, arg3);
            _sb.AppendLine();
            _isOnNewLine = true;
            return this;
        }

        /// <inheritdoc cref="AppendFormat(StringBuilder, ReadOnlySpan{char}, ReadOnlySpan{char}, ReadOnlySpan{char}, ReadOnlySpan{char})"/>
        public SourceWriter WriteLine(string format, ReadOnlySpan<char> arg1, ReadOnlySpan<char> arg2 = default, ReadOnlySpan<char> arg3 = default) => WriteLine(formatSpan: format.AsSpan(), arg1, arg2, arg3);


        /// <summary> Write a single char then moves to the next line. </summary>
        public SourceWriter WriteLine(char value)
        {
            if (_isOnNewLine && _indentation > 0) Indent();
            _sb.Append(value);
            _sb.AppendLine();
            _isOnNewLine = true;
            return this;
        }
        
        /// <summary>
        /// Writes a line of text. Evaluates the text, ensuring even indentation across multiple lines if the text has multiple lines.
        /// </summary>
        public SourceWriter WriteLine(string text)
        {
            if (_indentation == 0)
            {
                _sb.AppendLine(text);
                _isOnNewLine = true;
                return this;
            }

            bool isFinalLine;
            ReadOnlySpan<char> remainingText = text.AsSpan();
            do
            {
                _token.ThrowIfCancellationRequested();
                ReadOnlySpan<char> nextLine = GetNextLine(ref remainingText, out isFinalLine);

                IndentIfOnNewLine();
                AppendSpan(_sb, nextLine);
                _sb.AppendLine();
                _isOnNewLine = true;
            }
            while (!isFinalLine);
            return this;
        }

        /// <inheritdoc cref="WriteLine(string, string[])"/>
        public SourceWriter WriteLine(string format, string arg1)
        {
            if (_isOnNewLine && _indentation > 0) Indent();
            _sb.AppendFormat(format, arg1);
            _sb.AppendLine();
            _isOnNewLine = true;
            return this;
        }

        /// <inheritdoc cref="WriteLine(string, string[])"/>
        public SourceWriter WriteLine(string format, string arg1, string arg2)
        {
            if (_isOnNewLine && _indentation > 0) Indent();
            _sb.AppendFormat(format, arg1, arg2);
            _sb.AppendLine();
            _isOnNewLine = true;
            return this;
        }

        /// <inheritdoc cref="WriteLine(string, string[])"/>
        public SourceWriter WriteLineIf(bool writeIfTrue, string format, string arg1 = "", string arg2 = "")
        {
            if (writeIfTrue) WriteLine(format, arg1, arg2);
            return this;
        }

        /// <inheritdoc cref="WriteLine(string, string[])"/>
        /// <param name="arg1"/><param name="trailingComma"/><param name="writeIfTrue"/>
        public SourceWriter WriteLineIf(bool writeIfTrue, string format, string arg1, bool trailingComma)
        {
            if (writeIfTrue)
            {
                if (_isOnNewLine && _indentation > 0) Indent();
                _sb.AppendFormat(format, arg1);
                if (trailingComma) _sb.Append(',');
                _sb.AppendLine();
                _isOnNewLine = true;
            }
            return this;
        }

        /// <summary>
        /// Write a formatted expression to the file.
        /// </summary>
        /// <remarks>The formatted expression should be on a single line.</remarks>
        /// <param name="format">A formatted expression that represents 1 line.</param>
        /// <param name="args"></param>
        /// <returns>The <see cref="SourceWriter"/></returns>
        public SourceWriter WriteLine(string format, params string[] args)
        {
            if (_isOnNewLine && _indentation > 0) Indent();
            _sb.AppendFormat(format, args);
            _sb.AppendLine();
            _isOnNewLine = true;
            return this;
        }

        /// <summary>
        /// Move the to next line.
        /// </summary>
        public SourceWriter WriteLine()
        {
            _sb.AppendLine();
            _isOnNewLine = true;
            return this;
        }

        /// <summary>
        /// Write a parameter using the specified <paramref name="format"/>
        /// </summary>
        /// <param name="parameterSymbol"></param>
        /// <param name="format"></param>
        /// <param name="includeSeparator">set true to append ", " after the parameter</param>
        /// <param name="asNewLine">
        /// <see langword="true"/> : {indent} {parameter} {newline}
        /// <br/> <see langword="false"/> : {parameter}
        /// </param>
        /// <param name="defaultValue">default text string " = text" to append if the parameter does not have an <see cref="IParameterSymbol.HasExplicitDefaultValue"/></param>
        /// <returns></returns>
        public SourceWriter WriteSymbol(IParameterSymbol parameterSymbol, SymbolDisplayFormat format, bool includeSeparator, bool asNewLine, string defaultValue = "")
        {
            if (asNewLine && _indentation > 0) IndentIfOnNewLine();
            _isOnNewLine = false;
            _sb.Append(parameterSymbol.ToDisplayString(format));
            if (string.IsNullOrWhiteSpace(defaultValue) == false && (!parameterSymbol.HasExplicitDefaultValue | !format.ParameterOptions.HasFlag(SymbolDisplayParameterOptions.IncludeDefaultValue)))
            {
                _sb.Append(defaultValue);
            }
            if (includeSeparator) _sb.Append(", ");
            if (asNewLine)
            {
                _sb.AppendLine();
                _isOnNewLine = true;
            }
            return this;
        }

        /// <summary>
        /// Write a method invoker
        /// </summary>
        /// <param name="methodSymbol">the method to write</param>
        /// <param name="prefix">A prefix to write before writing the method display string.</param>
        /// <param name="format">
        /// The format to write the method with.
        /// <br/> - <see cref="SymbolFormats.MethodInvokeFullyQualified"/>
        /// <br/> - <see cref="SymbolFormats.MethodInvokePrivate"/>
        /// </param>
        /// <param name="isStartOfLine">if true indents the line.</param>
        /// <param name="isEndOfLine">if true : ends the line with ";"</param>
        /// <returns></returns>
        public SourceWriter WriteSymbol(IMethodSymbol methodSymbol, SymbolDisplayFormat format, bool isStartOfLine, bool isEndOfLine, string prefix = "")
        {
            if (isStartOfLine && _indentation > 0) IndentIfOnNewLine();
            _isOnNewLine = false;
            if (!string.IsNullOrWhiteSpace(prefix)) _sb.Append(prefix);
            _sb.Append(methodSymbol.ToDisplayString(format));
            if (isEndOfLine)
            {
                _sb.Append(';').AppendLine();
                _isOnNewLine = true;
            }
            return this;
        }

        /// <summary>
        /// Writes the method signature based on the provided formats
        /// </summary>
        /// <param name="methodSymbol"></param>
        /// <param name="methodFormat">the method format to apply</param>
        /// <param name="returnTypeFormat">optional return type format. use null if not specified.</param>
        /// <param name="parameterFormat">optional parameter format to apply to each parameter. If not null, also adds the () to the writer.</param>
        /// <param name="isPartialMethod">if true, indents the line and adds 'partial' before the return type.</param>
        /// <remarks>Does NOT move to the next line.</remarks>
        public SourceWriter WriteSymbol(IMethodSymbol methodSymbol, SymbolDisplayFormat methodFormat, SymbolDisplayFormat? returnTypeFormat = null, SymbolDisplayFormat? parameterFormat = null, bool isPartialMethod = false)
        {
            var membersToExclude = parameterFormat is null ? SymbolDisplayMemberOptions.None : SymbolDisplayMemberOptions.IncludeParameters;

            // write the method signature
            if (isPartialMethod || methodSymbol.IsPartialDefinition)
            {
                if (_isOnNewLine && _indentation > 0) Indent();
                if (methodFormat.MemberOptions.HasFlag(SymbolDisplayMemberOptions.IncludeModifiers))
                {
                    WriteSymbolModifiers(methodSymbol, isPartialMethod);
                    membersToExclude |= SymbolDisplayMemberOptions.IncludeModifiers;
                }
                else
                {
                    _sb.Append("partial ");
                }
            }
            _isOnNewLine = false;

            if (returnTypeFormat is not null)
            {
                _sb.Append(methodSymbol.ReturnType.ToDisplayString(returnTypeFormat)).Append(' ');
                membersToExclude |= SymbolDisplayMemberOptions.IncludeType;
            }

            if (membersToExclude != SymbolDisplayMemberOptions.None)
            {
                methodFormat = methodFormat.WithMemberOptions(methodFormat.MemberOptions & ~membersToExclude);
            }
            _sb.Append(methodSymbol.ToDisplayString(methodFormat));
            if (parameterFormat is not null)
            {
                _sb.Append('(');
                int lastParam = methodSymbol.Parameters.Length - 1;
                for (int i = 0; i < methodSymbol.Parameters.Length; i++)
                {
                    WriteSymbol(methodSymbol.Parameters[i], parameterFormat, i < lastParam, false);
                }
                _sb.Append(')');
            }
            return this;
        }

        /// <summary>
        /// Writes the <see cref="ISymbol"/> modifiers
        /// <br/> <see langword="internal, public, private, static, abstract, virtual, override, sealed, extern, async, partial"/>
        /// </summary>
        /// <param name="isPartial">include the 'partial' keyword or not</param>
        /// <returns></returns>
        public SourceWriter WriteSymbolModifiers(ISymbol symbol, bool isPartial = false)
        {
            WriteIndent();
            switch (symbol.DeclaredAccessibility)
            {
                case Accessibility.NotApplicable: break;
                case Accessibility.ProtectedOrInternal: _sb.Append("protected internal "); break;
                case Accessibility.ProtectedAndInternal: _sb.Append("private protected "); break;
                case Accessibility.Protected: _sb.Append("protected "); break;
                case Accessibility.Internal: _sb.Append("internal "); break;
                case Accessibility.Private: _sb.Append("private "); break;
                case Accessibility.Public: _sb.Append("public "); break;
            }
            if (symbol.IsStatic) _sb.Append("static ");
            if (symbol.IsAbstract || symbol.IsVirtual || symbol.IsOverride) _sb.Append("override ");
            if (symbol.IsSealed) _sb.Append("sealed ");
            if (symbol.IsExtern) _sb.Append("extern ");
            if (symbol is IMethodSymbol ms)
            {
                if (ms.IsAsync) _sb.Append("async ");
                if (ms.IsPartialDefinition || isPartial) _sb.Append("partial ");
            }
            else if (isPartial)
            {
                _sb.Append("partial ");
            }
            _isOnNewLine = false;
            return this;
        }

        /// <summary>
        /// Add indentation to the start of the current line.
        /// </summary>
        public SourceWriter WriteIndent()
        {
            if (_isOnNewLine && _indentation > 0) Indent();
            return this;
        }

        private static ReadOnlySpan<char> GetNextLine(ref ReadOnlySpan<char> remainingText, out bool isFinalLine)
        {
            if (remainingText.IsEmpty)
            {
                isFinalLine = true;
                return default;
            }

            ReadOnlySpan<char> next;
            ReadOnlySpan<char> rest;

            int lineLength = remainingText.IndexOf('\n');
            if (lineLength == -1)
            {
                lineLength = remainingText.Length;
                isFinalLine = true;
                rest = default;
            }
            else
            {
                rest = remainingText.Slice(lineLength + 1);
                isFinalLine = false;
            }

            if ((uint)lineLength > 0 && remainingText[lineLength - 1] == '\r')
            {
                lineLength--;
            }

            next = remainingText.Slice(0, lineLength);
            remainingText = rest;
            return next;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static unsafe void AppendSpan(StringBuilder builder, ReadOnlySpan<char> span)
        {
            // There is no StringBuilder.Append(ReadOnlySpan<char>) overload in the NS2.0
            fixed (char* ptr = span)
            {
                builder.Append(ptr, span.Length);
            }
        }

        static ReadOnlySpan<char> ThrowOutOfRange(ReadOnlySpan<char> argIndex)
        {
            throw new ArgumentOutOfRangeException("format", $"Format index {{{new string(argIndex.ToArray())}}} is out of range.");
        }

        /// <summary>
        /// Appends a formatted string to the StringBuilder using <see langword="ReadOnlySpan{char}"/> arguments
        /// <br/>Supports only simple numbered placeholders: {0}, {1}, {2}.
        /// </summary>
        public static void AppendFormat(StringBuilder sb, ReadOnlySpan<char> format, ReadOnlySpan<char> arg1, ReadOnlySpan<char> arg2 = default, ReadOnlySpan<char> arg3 = default)
        {
            int i = 0;
            while (i < format.Length)
            {
                char c = format[i];

                if (c == '{')
                {
                    int start = ++i; // move past '{'

                    // find matching '}'
                    while (i < format.Length && format[i] != '}')
                        i++;

                    if (i >= format.Length)
                        throw new FormatException("Input string was not in a correct format: missing closing brace '}'.");

                    // parse placeholder number
                    var argIndex = format.Slice(start, i - start);
                    
                    
                    if (argIndex.Length > 1)
                    {
                        ThrowOutOfRange(argIndex);
                    }
                    ReadOnlySpan<char> arg = argIndex[0] switch
                    {
                        '0' => arg1,
                        '1' => arg2,
                        '2' => arg3,
                        _ => ThrowOutOfRange(argIndex)
                    };
                    AppendSpan(sb, arg);
                    i++; // skip '}'
                }
                else
                {
                    // append literal segment
                    int start = i;
                    while (i < format.Length && format[i] != '{')
                        i++;

                    AppendSpan(sb, format.Slice(start, i - start));
                }
            }
        }
    }
}